# Generated by Django 4.1.7 on 2023-03-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_project_author_userproject_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to='webapp.project', verbose_name='Проект'),
        ),
    ]
